name: Build and deploy Project Zoe client

on:
  push:
    branches: [ master, develop, feat/upgrade-react-scripts-5 ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install   
          
    #- name: Run the tests and generate coverage report
    #  run: npm test -- --coverage
#
    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v1
          
      # Temporarily skip eslint by using DISABLE_ESLINT_PLUGIN
      - name: Build
        run: |
          DISABLE_ESLINT_PLUGIN=true npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy the app
        uses: garygrossgarten/github-action-scp@release
          with:
            local: ./build
            remote: /var/www/html/projectzoe.kanzucodefoundation.org
            host: ${{secrets.DO_HOST}}
            username: ${{secrets.DO_USERNAME}}
            privateKey: ${{secrets.DO_PRIVATE_KEY}}